// Time Rush — Default Store Data (can be overridden from Admin Dashboard)
// NOTE: This is a static demo store. Products are saved in the browser (localStorage).

window.TR_DEFAULT_SETTINGS = {
  storeName: "Time Rush",
  tagline: "Luxury Watches",
  currencySymbol: "$",
  currencyCode: "USD",
  contactEmail: "timerush11@gmail.com",
  shippingNote: "Fast delivery • Cash on delivery available (depending on area)",
  whatsapp: "",
  instagram: "",
  addressLine: "",
};

window.TR_DEFAULT_PRODUCTS = [
  {
    id: "tr-001",
    name: "SKMEI Compass Dual Display — Black",
    brand: "SKMEI",
    category: "featured",
    price: 29.99,
    compareAtPrice: 35.99,
    badge: "Sale",
    image: "assets/images/11.png",
    images: ["assets/images/11.png"],
    shortDescription: "Analog + digital sport watch with compass-style bezel.",
    description:
      "A bold analog-digital design inspired by outdoor instruments. Clean legibility, strong presence, and daily-ready functions.",
    highlights: ["Analog + digital display", "LED backlight", "Alarm + stopwatch", "5 BAR water resistance"],
    specs: {
      Movement: "Quartz",
      Display: "Analog + digital",
      "Water Resistance": "5 BAR",
      Strap: "Resin",
      Case: "Resin",
    },
  },
  {
    id: "tr-002",
    name: "SKMEI Compass Dual Display — Olive",
    brand: "SKMEI",
    category: "featured",
    price: 29.99,
    compareAtPrice: 35.99,
    badge: "Sale",
    image: "assets/images/12.png",
    images: ["assets/images/12.png"],
    shortDescription: "Outdoor-inspired dual display with olive strap.",
    description:
      "The olive edition delivers a rugged look with the same dual-display convenience—perfect for sport, streetwear, and everyday use.",
    highlights: ["Dual display", "Backlight", "Alarm + chrono", "5 BAR water resistance"],
    specs: {
      Movement: "Quartz",
      Display: "Analog + digital",
      "Water Resistance": "5 BAR",
      Strap: "Resin",
      Case: "Resin",
    },
  },
  {
    id: "tr-003",
    name: "SKMEI Dual Time EL Luminous — Black",
    brand: "SKMEI",
    category: "sport",
    price: 24.99,
    compareAtPrice: 0,
    badge: "New",
    image: "assets/images/13.png",
    images: ["assets/images/13.png"],
    shortDescription: "Square sporty digital with dual time & countdown.",
    description:
      "Compact square digital style with dual time and practical functions. Designed to be worn daily and to handle active routines.",
    highlights: ["Dual time", "Countdown timer", "Alarm", "EL luminous"],
    specs: {
      Movement: "Quartz",
      Display: "Digital",
      "Water Resistance": "WR50M",
      Functions: "Alarm, chronograph, timer",
    },
  },
  {
    id: "tr-004",
    name: "SKMEI Dual Time EL Luminous — Olive",
    brand: "SKMEI",
    category: "sport",
    price: 24.99,
    compareAtPrice: 0,
    badge: "New",
    image: "assets/images/14.png",
    images: ["assets/images/14.png"],
    shortDescription: "Military olive digital with clean screen contrast.",
    description:
      "Olive colorway with a crisp display layout. A practical piece with everyday timers, alarms and a comfortable strap.",
    highlights: ["Dual time", "Stopwatch", "Timer", "WR50M"],
    specs: {
      Movement: "Quartz",
      Display: "Digital",
      "Water Resistance": "WR50M",
      Strap: "Resin",
    },
  },
  {
    id: "tr-005",
    name: "Naviforce Roman Dial — Grey Leather",
    brand: "Naviforce",
    category: "classic",
    price: 39.99,
    compareAtPrice: 0,
    badge: "Classic",
    image: "assets/images/4.png",
    images: ["assets/images/4.png"],
    shortDescription: "Textured dial with Roman numerals and date window.",
    description:
      "A refined everyday classic with a textured dial, Roman numeral accents, and a comfortable leather strap.",
    highlights: ["Date window", "Roman numeral markers", "Textured dial", "Leather strap"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Leather",
      "Water Resistance": "30M",
    },
  },
  {
    id: "tr-006",
    name: "Naviforce Textured Dial — Steel Black",
    brand: "Naviforce",
    category: "classic",
    price: 44.99,
    compareAtPrice: 0,
    badge: "Best Seller",
    image: "assets/images/7.png",
    images: ["assets/images/7.png"],
    shortDescription: "Steel bracelet with bold texture and date.",
    description:
      "Sleek steel build with a textured center dial and strong markers. A versatile look from office to night.",
    highlights: ["Steel bracelet", "Date window", "Textured dial", "Strong readability"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Stainless steel",
      "Water Resistance": "30M",
    },
  },
  {
    id: "tr-007",
    name: "Curren Steel — White Dial",
    brand: "CURREN",
    category: "classic",
    price: 34.99,
    compareAtPrice: 0,
    badge: "Elegant",
    image: "assets/images/5.png",
    images: ["assets/images/5.png"],
    shortDescription: "Clean white dial with steel bracelet and date.",
    description:
      "Minimal white dial with a classic steel bracelet—an easy match for formal and casual outfits.",
    highlights: ["Date window", "Minimal dial", "Steel bracelet"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Stainless steel",
    },
  },
  {
    id: "tr-008",
    name: "Curren Steel — Black Dial",
    brand: "CURREN",
    category: "classic",
    price: 34.99,
    compareAtPrice: 0,
    badge: "Elegant",
    image: "assets/images/6.png",
    images: ["assets/images/6.png"],
    shortDescription: "Black dial steel watch with a timeless profile.",
    description:
      "A timeless black dial in a clean steel frame. Balanced proportions and daily reliability.",
    highlights: ["Date window", "Minimal dial", "Steel bracelet"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Stainless steel",
    },
  },
  {
    id: "tr-009",
    name: "Yazole Minimal — White Dial Brown Strap",
    brand: "Yazole",
    category: "classic",
    price: 19.99,
    compareAtPrice: 0,
    badge: "Classic",
    image: "assets/images/10.png",
    images: ["assets/images/10.png"],
    shortDescription: "Ultra-clean dial with warm brown strap.",
    description:
      "A minimalist face with warm contrast. Perfect for a smart-casual everyday look.",
    highlights: ["Minimal design", "Leather strap", "Lightweight feel"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Leather",
    },
  },
  {
    id: "tr-010",
    name: "Yazole Minimal — Black Dial Black Strap",
    brand: "Yazole",
    category: "classic",
    price: 19.99,
    compareAtPrice: 0,
    badge: "Classic",
    image: "assets/images/8.png",
    images: ["assets/images/8.png"],
    shortDescription: "Minimal black dial with matching strap.",
    description:
      "Understated and clean. The all-black minimalist look that goes with anything.",
    highlights: ["Minimal design", "Leather strap", "Easy styling"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Leather",
    },
  },
  {
    id: "tr-011",
    name: "Yazole Full Black — Stealth Edition",
    brand: "Yazole",
    category: "classic",
    price: 21.99,
    compareAtPrice: 0,
    badge: "Stealth",
    image: "assets/images/9.png",
    images: ["assets/images/9.png"],
    shortDescription: "Dark case with minimal markers for a stealth look.",
    description:
      "A darker, more stealthy version of the minimalist lineup. Bold yet understated.",
    highlights: ["Stealth all-black finish", "Minimal markers", "Comfort strap"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Leather",
    },
  },
  {
    id: "tr-012",
    name: "Sport Octagon — Matte Black",
    brand: "Time Rush",
    category: "featured",
    price: 31.99,
    compareAtPrice: 0,
    badge: "Featured",
    image: "assets/images/logo1.png",
    images: ["assets/images/logo1.png"],
    shortDescription: "Octagon case with modern dial details.",
    description:
      "A bold octagon case with a modern sport silhouette. Lightweight strap and strong wrist presence.",
    highlights: ["Sport silhouette", "Comfort strap", "Modern case"],
    specs: {
      Movement: "Quartz",
      Display: "Analog + digital",
      Strap: "Resin",
    },
  },
  {
    id: "tr-013",
    name: "Curren Sport Rubber — Black",
    brand: "CURREN",
    category: "sport",
    price: 27.99,
    compareAtPrice: 0,
    badge: "Sport",
    image: "assets/images/logo2.png",
    images: ["assets/images/logo2.png"],
    shortDescription: "Rubber strap with textured dial and date.",
    description:
      "Sport-ready feel with a rubber strap and textured dial. Built for comfort and daily wear.",
    highlights: ["Rubber strap", "Textured dial", "Date window"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Rubber",
    },
  },
  {
    id: "tr-014",
    name: "Yazole Classic — Silver Brown",
    brand: "Yazole",
    category: "classic",
    price: 22.99,
    compareAtPrice: 0,
    badge: "Classic",
    image: "assets/images/3.png",
    images: ["assets/images/3.png"],
    shortDescription: "Silver case with warm brown leather.",
    description:
      "A refined silver case and warm leather strap. Clean markers and balanced proportions.",
    highlights: ["Leather strap", "Clean markers", "Comfort fit"],
    specs: {
      Movement: "Quartz",
      Display: "Analog",
      Strap: "Leather",
    },
  },
];
